apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: measure-yolo
  namespace: serverless
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "0"
        autoscaling.knative.dev/window: "10s"
    spec:
      # Forces pods to run on the specific node
      nodeSelector:
        kubernetes.io/hostname: "cloud-node"
      containers:
        - image: docker.io/lazyken/measure-yolo:v1@sha256:31a9a8a56a37f5bca6ca885b597933b09ad687bffa7b30cae9c0ca8e65b25028
          ports:
            - containerPort: 8080
          env:
            - name: RTMP_STREAM_URL
              value: '192.168.17.130:2000'
            - name: MODEL_LOAD_TIMEOUT
              value: '0'
          # resources:
          #   limits:
          #     cpu: "100m"   
          #     memory: "3Gi"  